### ISSUE TITLE
Why render depth images?

### ISSUE THREAD

**Issue by Pixie8888** [tyhuang0428/CLIP2Point#6]
Hi,

I am confused why must render the (sparse) depth images? Why can't use the (dense) depth images provided in the datasets?

I have an another question about the few-shot setting. Do you only finetune f_1^C, f_2^C, f_1^D, f_2^D (eqn17, 18) in the few-shot learning?

**Comment by tyhuang0428** [comment]
1) To conduct a fair comparison, methods usually use the same number of points for classification, e.g., 1k points in ModelNet40.

2) Yes, we only fine-tune those parameters. You can refer to the [codes](https://github.com/tyhuang0428/CLIP2Point/blob/main/models/dpa.py#L23).
